config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'home' => 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  root 'static_pages#home'

  resources :users, only: [:index, :show] do
    resources :requests, except: [:edit, :update]
    resources :favorites, only: [:index]
  end

  get '/users/:id/:show_type' => 'relationships#index'

  resources :relationships, only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]

  resources :categories

  resources :books

  resources :comments

  resources :read_statuses

  get 'history' => 'read_statuses#index'

  resources :favorites, only: [:create, :destroy]

  resources :reviews, only: [:create, :update, :destroy]

  namespace :admin do
    root 'static_pages#home'
    resources :users, only: :destroy
    resources :requests, only: [:index, :show, :update]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :read_statuses, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: {maximum: 30}

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  def is_admin_user?
    admin?
  end

  def feed
    followed_ids = Relationship.followed_of(id).pluck :followed_id
    users_ids = followed_ids.push id
    Activity.owned_by users_ids
  end

  def like_activity activity
    likes.create user_id: id, activity_id: activity.id
  end

  def unlike_activity activity
    likes.find_by(user_id: id, activity_id: activity.id).destroy
  end

  def favorite_book book
    favorites.create user_id: id, book_id: book.id
  end

  def remove_favorite favorite
    favorites.find_by(id: favorite.id).destroy
  end

  def favorite? book
    book_ids = favorites.pluck :book_id
    book_ids.include? book.id
  end

  def favorite_of book
    favorite_list = favorites.where book_id: book.id
    favorite_list.first
  end

  def reviewed? book
    reviews.find_by(book_id: book.id).present?
  end

  def own_review? review
    reviews.find_by(id: review.id).present?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:success] = "User deleted!"
    redirect_to users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :load_activities, only: [:show]

  def index
    @users = User.all.paginate page: params[:page], per_page: 10
  end

  def show
  end

  private

  def load_activities
    @user = User.find params[:id]
    if current_user == @user || current_user.following?(@user)
      @activities = @user.activities.order(created_at: :desc)
                                    .paginate page: params[:page], per_page: 20
    else
      @activities = []
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.eql? @user %>
  <div class="follow_form">
  <% if current_user.following? @user %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), method: :delete) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li class = "user_info">
  <%= gravatar_for(user, size: 50) %>
  <%= link_to user.name, user %>
  <% if current_user.is_admin_user? %>
    <span>
      | <%= link_to "Delete", admin_user_path(user), method: :delete,
                                      data: {confirm: "You sure?"} %>
    </span>
  <% end %>
</li>

app/views/users/index.html.erb
<% provide :title, 'All users' %>
<div class="row">
  <h1>All users</h1>

  <%= will_paginate %>

  <ul class="users">
    <%= render @users %>
  </ul>

  <%= will_paginate %>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>

<div class="row">
  <aside class="col-md-4">
    <%= render 'shared/user_info' %>
    <%= render 'follow_form' %>
  </aside>
  <aside class="col-md-8">
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if @user == current_user %>
          <li><%= link_to "Requests", user_requests_path(@user) %></li>
        <% end %>
        <li><%= link_to "Favourite books", user_favorites_path(@user) %></li>
      </ul>
    </div>
    <div class="list-activities-div">
      <% if @activities.any? %>
        <h2>Activities</h2>
        <ol class="list-activities">
          <%= render @activities %>
          <%= will_paginate @activities %>
        </ol>
      <% end %>
    </div>
  </aside>
</div>