config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'home' => 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  root 'static_pages#home'

  resources :users, only: [:index, :show] do
    resources :requests, except: [:edit, :update]
    resources :favorites, only: [:index]
  end

  get '/users/:id/:show_type' => 'relationships#index'

  resources :relationships, only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]

  resources :categories

  resources :books

  resources :comments

  resources :read_statuses

  get 'history' => 'read_statuses#index'

  resources :favorites, only: [:create, :destroy]

  resources :reviews, only: [:create, :update, :destroy]

  namespace :admin do
    root 'static_pages#home'
    resources :users, only: :destroy
    resources :requests, only: [:index, :show, :update]
  end

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: {maximum: 100}
  validates :content, presence: true, length: {maximum: 300}

  def pending?
    solve == "pending"
  end
end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
    @requests = Request.all.order created_at: :desc
    @requests = @requests.paginate page: params[:page], per_page: 20
  end

  def show
    @request = Request.find params[:id]
  end

  def update
    @request = Request.find params[:id]
    @request.update_attributes solve_param

    respond_to do |format|
      format.html {redirect_to admin_request_path @request}
      format.js
    end
  end

  private

  def admin_user
    redirect_to root_url unless current_user.is_admin_user?
  end

  def solve_param
    params.permit :solve
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user

  def index
    @user = User.find params[:user_id]
    @requests = @user.requests.order created_at: :desc
    @requests = @requests.paginate page: params[:page], per_page: 10
  end

  def create
    @user = User.find params[:user_id]
    @request = @user.requests.build request_params
    if @request.save
      flash[:success] = "Request created!"
      redirect_to user_requests_path @user
    else
      render 'new'
    end
  end

  def new
    @user = User.find params[:user_id]
    @request = Request.new
  end

  def show
    @user = User.find params[:user_id]
    @request = Request.find params[:id]
  end

  def destroy
    @request = Request.find params[:id]
    @request.destroy
    flash[:success] = "Request cancelled"
    redirect_to user_requests_path
  end

  private

  def request_params
    params.require :user_id
    params.require(:request).permit :title, :content
  end

  def correct_user
    @user = User.find params[:user_id]
    redirect_to root_url unless current_user == @user
  end
end

app/views/requests/_request.html.erb
<li class="request-show">
  <div class="request-title-div">
    <span class="request-title">
      <%= link_to request.title, user_request_path(@user, request) %>
      <%= "(#{request.solve})" %>
    </span>
  </div>
  <div class="request-cancel-div">
    <% if request.pending? %>
      <span class="request-cancel">
        <%= link_to "Cancel", user_request_path(@user, request), method: :delete, data: {confirm: "Are you sure?"} %>
      </span>
    <% end %>
  </div>
  <div class="request-content-div">
    <span class="request-content">
      <%= request.content %>
    </span>
  </div>
</li>

app/views/requests/index.html.erb
<% provide :title, "Requests of #{@user.name}" %>

<div class="row">
  <aside class="col-md-4">
    <%= render 'shared/user_info' %>
  </aside>
  <aside class="col-md-8">
    <div class="create-request-link-div">
      <%= link_to "Create new request", new_user_request_path(@user) %>
    </div>
    <div class="list-requests-div">
      <% if @requests.any? %>
        <h2>Requests</h2>
        <ol class="requests">
          <%= render @requests, user: @user %>
          <%= will_paginate @requests %>
        </ol>
      <% end %>
    </div>
  </aside>
</div>

app/views/requests/new.html.erb
<% provide :title, "New request" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>New Request</h2>
    <%= form_for [@user, @request] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control" %>

      <%= f.submit "Create request", class: "button btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/requests/show.html.erb
<% provide :title, "Request of #{@user.name}" %>

<div class="row">
  <aside class="col-md-4">
    <%= render 'shared/user_info' %>
  </aside>
  <aside class="col-md-8">
    <div class="request-title-div">
      <span class="request-title">
        <%= link_to @request.title, user_request_path(@user, @request) %>
        <%= "(#{@request.solve})" %>
      </span>
    </div>
    <div class="request-cancel-div">
      <% if @request.pending? %>
        <span class="request-cancel">
          <%= link_to "Cancel", user_request_path(@user, @request),
                      method: :delete, data: {confirm: "Are you sure?"} %>
        </span>
      <% end %>
    </div>
    <div class="request-content-div">
      <span class="request-content">
        <%= @request.content %>
      </span>
    </div>
    <div class="request-images-div">
    </div>
  </aside>
</div>